name: Bug report
description: 🐞 Create a report to help us improve
title: "[Bug report]"
labels:
  - bug
assignees: Bellyang
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Make sure that you follow these statements.
      options:
        - label: I am using the **latest version**
          required: true
        - label: I have searched [Docs](https://mopo-cli.vercel.app/)
          required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: |
        Please provide the version used. Note: if it is not the latest version, you can try to upgrade to the latest version and check if the problem still exists.
      placeholder: |
        e.g. 1.1.2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🔎 Description
      description: A clear and concise description of what the bug is.And input a clear and concise description of what you expected to happen.
      value: "#### Concise Description\n\n#### Expected behavior\n\n#### Steps to reproduce\n\n#### Screenshots or Screen Recording(if possible)"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Need to provide reproduction steps to help us quickly find the problem. Note: you can use [Markdown](https://guides.github.com/features/mastering-markdown/) to format lists and code.
      placeholder: |
        1. Steps to reproduce the issue
        2. Content of mopo.config.js configuration file
        3. Whether additional configuration files were added(eg: eslint.config.js)
        4. Whether the repository or project directory was modified and what changes were made
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: "🔗 Reproduction link / repo:"
      description: If applicable, give us the project address, or minimize test cases repo to help us explain your problem.
      placeholder: "link / repo URL"